"""Keep source boundaries visible around Docling's native HTML serialization."""

from __future__ import annotations

import html
import re
from pathlib import Path
from typing import Any

from docling_core.transforms.serializer.base import BaseDocSerializer, SerializationResult
from docling_core.transforms.serializer.html import (
    HTMLDocSerializer,
    HTMLParams,
    HTMLTableSerializer,
)
from docling_core.types.doc import DocItem, DoclingDocument, ImageRefMode, TableItem

from docling_desk.documents.evidence import OCR_META

BOUNDARY_STYLE = """<style>
body{padding:14px;background:#edf1f4;max-width:100%;box-sizing:border-box}
.boundary-nav{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px;font-size:12px}
.boundary-nav a{color:#235464;background:white;border:1px solid #becfd6;border-radius:4px;padding:4px 8px;text-decoration:none}
.boundary-note{font-size:12px;color:#685222;background:#fff8eb;padding:10px;line-height:1.6}
.extracted-page{background:white;border:1px solid #b9cbd3;border-radius:7px;margin:0 0 26px;overflow:hidden;break-after:page;scroll-margin-top:10px}
.extracted-page:last-child{break-after:auto}
.page-boundary{background:#173f4b;color:white;padding:10px 14px;font-size:13px;font-weight:600;border-bottom:1px solid #b9cbd3}
.extracted-page>.page{padding:18px;margin:0}
.empty-page{color:#677b86;font-size:13px;padding:18px}
@media print{body{padding:0;background:white}.boundary-nav{display:none}.extracted-page{border:0;border-radius:0;margin:0}.page-boundary{color:black;background:white;border-bottom:1px solid #888}}
</style>"""


class ReferencedTableSerializer(HTMLTableSerializer):
    """Attach stable references to native tables, rather than guessing by DOM order."""

    def serialize(
        self,
        *,
        item: TableItem,
        doc_serializer: BaseDocSerializer,
        doc: DoclingDocument,
        **kwargs: Any,
    ) -> SerializationResult:
        result = super().serialize(item=item, doc_serializer=doc_serializer, doc=doc, **kwargs)
        result.text = result.text.replace(
            "<table>", f'<table data-docling-ref="{html.escape(item.self_ref, quote=True)}">', 1
        )
        return result


def referenced_html(doc: DoclingDocument, page_no: int | None = None) -> str:
    return (
        HTMLDocSerializer(
            doc=doc,
            table_serializer=ReferencedTableSerializer(),
            params=HTMLParams(
                html_lang="ja",
                image_mode=ImageRefMode.EMBEDDED,
                pages={page_no} if page_no is not None else None,
                blocked_meta_names={OCR_META},
            ),
        )
        .serialize()
        .text
    )


def html_parts(raw: str) -> tuple[str, str]:
    """Split the predictable head/body generated by Docling, not arbitrary uploads."""
    head = re.search(r"<head\b[^>]*>(.*?)</head>", raw, re.S | re.I)
    body = re.search(r"<body\b[^>]*>(.*?)</body>", raw, re.S | re.I)
    if head is None or body is None:
        raise ValueError("Docling HTML export did not contain a head and body")
    return head.group(1), body.group(1)


def sheet_names(doc: DoclingDocument) -> dict[int, str]:
    names: dict[int, str] = {}
    for group in doc.groups:
        if group.label.value != "sheet":
            continue
        for item, _ in doc.iterate_items(root=group):
            if isinstance(item, DocItem) and item.prov:
                names[item.prov[0].page_no] = group.name
    return names


def unlocated_html(doc: DoclingDocument) -> str:
    """Do not silently drop standalone content with no source-page provenance."""
    serializer = HTMLDocSerializer(
        doc=doc,
        table_serializer=ReferencedTableSerializer(),
        params=HTMLParams(
            html_lang="ja", image_mode=ImageRefMode.EMBEDDED, blocked_meta_names={OCR_META}
        ),
    )
    excluded = serializer.get_excluded_refs()
    parts: list[str] = []
    for item, _ in doc.iterate_items():
        if not isinstance(item, DocItem) or item.prov or item.self_ref in excluded:
            continue
        # A caption or child of another DocItem is serialized with that ancestor.
        ancestor = item.parent.resolve(doc) if item.parent is not None else None
        has_item_ancestor = False
        while ancestor is not None:
            if isinstance(ancestor, DocItem):
                has_item_ancestor = True
                break
            ancestor = ancestor.parent.resolve(doc) if ancestor.parent is not None else None
        if not has_item_ancestor:
            parts.append(serializer.serialize(item=item).text)
    return "\n".join(parts)


def render_paginated_html(doc: DoclingDocument, filename: str) -> str:
    page_numbers = sorted(doc.pages)
    suffix = Path(filename).suffix.lower()
    unit = {".pptx": "スライド", ".xlsx": "シート"}.get(suffix, "ページ")
    names = sheet_names(doc) if suffix == ".xlsx" else {}
    sections: list[str] = []
    links: list[str] = []
    head = ""
    if not page_numbers:
        head, body = html_parts(referenced_html(doc))
        sections.append(
            '<section class="extracted-page" data-page="unknown">'
            '<header class="page-boundary">ページ境界未取得</header>' + body + "</section>"
        )
    for index, page_no in enumerate(page_numbers, start=1):
        head, body = html_parts(referenced_html(doc, page_no))
        # Loaded JSON and converter documents retain embedded picture references.
        label = f"{unit} {page_no}"
        if page_no in names:
            label += f" · {names[page_no]}"
        label += f"（{index} / {len(page_numbers)}）"
        safe_label = html.escape(label)
        links.append(f'<a href="#extracted-page-{page_no}">{safe_label}</a>')
        if not any(
            isinstance(item, DocItem) and item.prov and item.prov[0].page_no == page_no
            for item, _ in doc.iterate_items()
        ):
            body = '<p class="empty-page">この位置から抽出できた本文・表・図はありません。</p>'
        sections.append(
            f'<section class="extracted-page" id="extracted-page-{page_no}" data-page="{page_no}">'
            f'<header class="page-boundary">{safe_label}</header>{body}</section>'
        )
    if page_numbers and (unknown := unlocated_html(doc)):
        sections.append(
            '<section class="extracted-page" data-page="unknown">'
            '<header class="page-boundary">ページ境界未判定の要素</header>'
            '<div class="page">' + unknown + "</div></section>"
        )
    notes: list[str] = []
    if suffix == ".xlsx":
        notes.append("表示の区切りはシート単位です。Excelの印刷ページ境界は取得していません。")
    if any(
        isinstance(item, DocItem) and len({p.page_no for p in item.prov}) > 1
        for item, _ in doc.iterate_items()
    ):
        notes.append("複数ページにまたがる要素は、Doclingの先頭の出典ページにまとめて表示します。")
    if not page_numbers:
        notes.append(
            "原本のページ位置を取得できていないため、本文の長さによるページ分割は行っていません。"
        )
    note_html = "".join(f'<p class="boundary-note">{html.escape(note)}</p>' for note in notes)
    navigation = '<nav class="boundary-nav" aria-label="抽出ページ">' + "".join(links) + "</nav>"
    return (
        '<!doctype html><html lang="ja"><head>'
        + head
        + BOUNDARY_STYLE
        + "</head><body>"
        + note_html
        + navigation
        + "".join(sections)
        + "</body></html>"
    )


def export_paginated_html(doc: DoclingDocument, filename: str, target: Path) -> None:
    target.write_text(render_paginated_html(doc, filename), encoding="utf-8")
